test: run desktop tests in pull requests to completion even with some suites fails

diff --git a/.github/workflows/desktop-linux-test-pull.yml b/.github/workflows/desktop-linux-test-pull.yml
--- a/.github/workflows/desktop-linux-test-pull.yml
+++ b/.github/workflows/desktop-linux-test-pull.yml
@@ -47,6 +47,8 @@ jobs:
 
       - name: Run tauri unit tests
         uses: nick-fields/retry@v2
+        id: linuxRunUnit
+        continue-on-error: true
         with:
           timeout_minutes: 12
           max_attempts: 3
@@ -54,6 +56,8 @@ jobs:
 
       - name: Run tauri integration tests
         uses: nick-fields/retry@v2
+        id: linuxRunIntegration
+        continue-on-error: true
         with:
           timeout_minutes: 12
           max_attempts: 3
@@ -61,6 +65,8 @@ jobs:
 
       - name: Run tauri mainview tests
         uses: nick-fields/retry@v2
+        id: linuxRunMainview
+        continue-on-error: true
         with:
           timeout_minutes: 12
           max_attempts: 3
@@ -68,6 +74,8 @@ jobs:
 
       - name: Run tauri livepreview tests
         uses: nick-fields/retry@v2
+        id: linuxRunLivepreview
+        continue-on-error: true
         with:
           timeout_minutes: 12
           max_attempts: 3
@@ -75,7 +83,15 @@ jobs:
 
       - name: Run tauri LegacyInteg tests
         uses: nick-fields/retry@v2
+        id: linuxRunLegacyInteg
+        continue-on-error: true
         with:
           timeout_minutes: 20
           max_attempts: 3
           command: xvfb-run ../phoenix-desktop/src-tauri/target/debug/phoenix-test --run-tests=LegacyInteg -q
+
+      - name: Fail on test runs failed in Linux
+        if: steps.linuxRunUnit.outcome == 'failure' || steps.linuxRunIntegration.outcome == 'failure' || steps.linuxRunMainview.outcome == 'failure' || steps.linuxRunLivepreview.outcome == 'failure' || steps.linuxRunLegacyInteg.outcome == 'failure'
+        run: |
+          echo "Linux tests failed, marking step as failed"
+          exit 1
